### ISSUE TITLE
Incompatible with nuxt 2.0

### ISSUE THREAD

**Issue by crstin** [nuxt-community/blog-module#11]
```
error TypeError: dep.getResourceIdentifier is not a function
```

<div align="right"><sub><em>This question is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/blog-module/issues/c7">#c7</a>)</em></sub></div>

**Comment by husayt** [comment]
Can you please provide some more context? e..g Where is the error from, what are you running and etc?

**Comment by crstin** [comment]
Excuse me, the error is on a basic level therefore I left out any further info.
It basically happens after a fresh `create-nuxt-app` with `nuxt 2`, adding the `blog-module` according to the guides and you can see it as soon as you run `yarn dev`. The node environment and dependencies are all latest stable.

**Comment by pinalbhatt** [comment]
yes this is still an issue... does anybody have workaround for this?

**Comment by pinalbhatt** [comment]
I think nuxtent-module can be answer to this. not tried it yet. Will try it out soon  and update here.

**Comment by renoirb** [comment]
I'm experiencing similar issue myself
