### ISSUE TITLE
Support for static sites

### ISSUE THREAD

**Issue by bayssmekanique** [nuxt-community/blog-module#8]
This module works very well when I'm running in development mode, but when I go to generate a static site, there are a few issues that I've noticed.

1. Navigating directly to a post via address works great, however, navigating to a post through any link makes a call to `/api/blog/posts/{slug}` which doesn't exist. 
2. Webpack does produce static JSON files which correspond to the `/api/blog/posts/{slug}` calls, but they are nested inside the public path directory (`/_nuxt`) and they have a `.json` extension added.
3. The `.json` files are not versioned in any way.  This is not a 100% deal breaker, since the corresponding `.html` files are no versioned either so they can share caching strategies, however it does go against the strategy of assuming everything in the pubilc path directory is versioned and thus can be cached for long periods.
4. Blog routes do not appear to play well with the `@nuxtjs/sitemap` module and don't appear within the `sitemap.xml` file or the `sitemap-routes.json` file.

In the few days I've spent pulling apart code, I have not been able to figure out a way to resolve any of these issues, as this module is failry large and complex.  I appreciate the capabilities but I don't know how useful it is without being able to function as a static file site.  I'll continue to work on it as time allows but I would be very interested in knowing if there is some configuration that I'm missing that might make some of these pieces fall into place.

**Comment by jewbetcha** [comment]
@bayssmekanique this is also happening to me! I've been searching everywhere for a solution to the `/api/` generated link issues. Any headway on that?
